apiVersion: v1
kind: Secret
metadata:
  name: jdownloader2-secret
stringData:
  VNC_PASSWORD: ENC[AES256_GCM,data:+3gjKWyVhtPWSJGAHf5G8w==,iv:G0EavH91yCE1Yai0RDBVKaFeiL9hYHACncGfXrt6BeM=,tag:u1fHhrUtSZAljNUox8fE9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGd1TGJpS1Jw
        YzA4WW5PZUdyVVFMS3VEajZPaXFMb3hxR1dLa1IrT0Iwc0RLcUh0RGFsd2hmZkFU
        Ym1jQ3dZeHVtNTZQb3dSZ1ZMQmR1eW0xTEROUE4zRVVVRFdGWWdWQVVqdUJtTVdN
        K2oydEh4eXNBVUNKOFBLbTExbExaR2ZLNVQrQ1JjZ1ZpRmgrWFM4MEMvb3dnYmhK
        cVpOUGZFaERpcmRySThlR1o3eS9Dam5PUzRycGZvQnV4NStsUis3RTArMEpaQWNO
        MDRteUdjOXZTMkp1SlkxR002U04xL3Vzb2RoeWFxd0R1Q0pHY1Y2R05EckIrdXBk
        QXpjdTg2ZUhWWkNObW16WWQvdWhzODZJTng5RDVqa3BQaG90RExSTXhKT1dQcFZX
        eVhJeG9kZFRKMGd1MnNyOW93dXlpM2ljM2FJYWwremk0ZTM5S3Q0YlI3eTUzWDN3
        OCszVDF3L0g2dm9iK2hnNEtGbEw2RDBGcXVyTlBHcHB0K2kvMnpCUDAzUXR2dW1Q
        bVp1RTV1aTZXK1lVUDA3TFlUUmdTNldBdUtYWS9rNm1Va0VnYkkxNFVodFN3b1Y3
        dzUrbHdxd05wUXZBcWJnaGE5dWFhcGgyZlF4N3ducXFKOUdhc3Z2bGM4NEJ3Q1V6
        SGU0QlhXNlViczA4QnFGc1F4N3U3R3FSbFZrTzczV2R4V2Y2dmNGZmg3dlZBQVQz
        T3hxcU9YZkRvd01RY2MzMUtJQnFJUGpYbjRJQkZBTlg0OXh0djZrQU5pUTZlTk9D
        REhLSW5Iajg4bVNHZ3MxTG1kWnlZSHd2VmVUc0NMVGs2NEovbW1BWEVXNEhUZmtx
        WTllWVpEZWlTc2E4WHZkNVl4Ymd1UEhlWnZqd1RBK01kaTBjMHFmcXZPcDdHeWps
        VTdMbUNvUFRZMXBEUWY4cnRKajlyYS9ienBNRFNndWRHTU5oYUowSFZCMHYzVUhQ
        cmhkN1pDTm5BL1N3a0NkcUR1RXprZkQ3UlhYOG5CTjFWQkVuRWN2MXhaTjhoTkMx
        WUJkMG5CVEdiNTN3YmRLbmNqUC9YYzB4TFhuZFlnVzZ3anpCRW42T3hvUnc2cHVQ
        VWpJK0o0WUQySS94dFRSdUlVTFRXMGFzOGhkRUxxcXFUQ1o5aUVCY3hiWGpha0RI
        OUx3MWUrQWczTDFzTGZuSkVwbEtzTkFJTE5ncEJNaFNmaFJBMzc0djdPeEV3NCsy
        c1hSNkhoQ1RPV2F5bGt3bGJsL0laanVYVzd2SXZOWmFXVnppK29oVndRT2hJYkJT
        b2VTMzVEdDI4SjREUGQrdkVlY0ttampKMW10dDE1VWdYKzhvdVZTL0hVMnJ0c1hF
        U2hDcU51R0h0RU1ET0IrZDFqcUdiSjd3M25uSTdhWnVjNUlmSXRoV2FhTXlZZ25m
        SFpiY3lZQ2ZFM0U5K3JVMEZ3aXUwZ1l2RlhicTZZaTl0MGxaeERnb0c1Y3FFRHBw
        d0EvYjlFR2d3bE00T0ZveHdaTStjWVllSFVGcEM5ZnVwSUh6STJERllVRWZJYnNj
        VmhtV0dMQ25rQkhLMEpHaGIzVXh6c0VZRml5YVJhaXlER0tNQmhwZitxMzNYeFhU
        UGdwR1dBMERoWW9OSmhZYlE0Uk5mWHhGNmJhQ0pmQ043WjlSV3FGMHdTMkp4ZmNH
        TWhsSFZ5ekQ1cmloM1hlTnZYZFRQbk1PU1F4enJpQXhObk5OajNUWmJ4Z0hvb2hv
        VmhET1VzU2RENDQza0k3Zll0Zm9SY0lGc04zY21TZjNpOVQrTmdvMXA2b2lhZ2Jr
        RlhpamJGYnpJRjFPTFhRRkZkdEdEQmNxaE9aT1pxKy95WS83R1huSEdiYXcyS1c1
        RUdreEdmLzU1dE42WVlnVVRRM1NYcXFHVXRrM1VxVGUzRjNjeGZRL3dXVDNTN25Q
        cHladE8rc3U1UHYvS1h1NHR3YjNhUFYrNHliMnFNUUxCY21UK1J2Ukp3RGtkdwp4
        UGZNUWdYMmNyU0M5bVl6NU9VZHNOMG9jNjVzMmV5TlY1VUZYS2xCVnI4Ci0tLSBG
        MGtNeTFnNjkvTTRhMGN5MnFueTdXbHF6ejhyVVVZWmtQdzNLRFRTYWc4CiE8YatL
        9jSp/h0/Fyxa48Dr4tNRi/2tod2meu9FZXlBg6ZIiPARFWBTyfQnULN7toiuTiJY
        0ZRmRKQmProQgr4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T19:57:24Z"
  mac: ENC[AES256_GCM,data:C/np25aX/XU6gB/aV/Nf0OTbdAsyO5mHdw68TU+xLfAofKUbhuRtZwweTBVK63dIXob3QTnQ0rMcLRUCVPZQ3jM/MU7ulbQFpGks7K8UqMomGJ+TcOUslo92MPSwOWWu3IEP2dCYlCoYW66zORWV6IhKSgfea/YyTluVc+6cEe4=,iv:yWAqlykVIdolXVHNiG2T4vBE5R06jgP1qyRKhI1GTLw=,tag:a8C1XTNDt66wdM0gV15+LA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
