---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: ${KOPIUR_NAME}
spec:
  policyRef:
    name: ${KOPIUR_NAME}
  schedule:
    cron: "${KOPIUR_CRON:=H H/12 * * *}" # every 12h, at a deterministic hashed minute/offset
