---
- name: automerge
  color: "0e8a16"
  description: Automatically merged when checks pass
- name: type/digest
  color: "ffeC19"
  description: Image or dependency digest update
- name: type/patch
  color: "ffeC19"
  description: Patch-level semver update
- name: type/minor
  color: "ff9800"
  description: Minor-level semver update
- name: type/major
  color: "f6412d"
  description: Major-level semver update
- name: renovate/container
  color: "5319e7"
  description: Container image updates
- name: renovate/helm
  color: "5319e7"
  description: Helm chart updates
- name: renovate/github-action
  color: "5319e7"
  description: GitHub Action updates
- name: renovate/github-release
  color: "5319e7"
  description: GitHub Release updates
