apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:I8aFnDyo8Z4pCxrA0aEFgoaiS3gjezEaMv3Zk42o/zNzyhIRl+aTy+fGRY1EFuppj2XLzYg=,iv:kWBZnXdpLUbuekslVYfyxAWRRbNCYqxIu5ctjJV9xYQ=,tag:BHvsNxzRLM6oNUzfYzmrXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZPcWtqdXhC
        eTNWNW5lWXpuWFFvSkVBb3JubUlqUFZzVWhwTm5kQmVuQmdmbjlyazhKeEQzYkJa
        VWU4cWJucVJ2MUVvSHIxSk12dWxxbnhVYkhxWDd4ZjNOekxydmVNRVpFR3lXWTFC
        WEtRL3FwYzdteFI4RGFVNExuanJXalB6U3czcFRHQWlWYVgwNlNIZzIxNWRPb2k3
        VWxYR0dnVEU4ZExnU0RyR1JMd3dvQUR1eXFYdEw0OHN1REdsMTA2S1hoNXpTQnpN
        ZDNvZHpNYkFCMys1TkJwMzAwaEVMR0QrYzl6WFB6ODUvb1FWQ2V1TTNneWZTYjA4
        aWhHb0doajd5SDg4VlJpV2VxeWJSdzM5Vi85b2RHUGlFeVlCNDdLVnJmQ0U3eVkw
        WVJ1VFNuZjQyNjVVQUF4QkdBUUY0dFFQdmYzZ1AvRS82d3A5Sk1oNHloZHI0NWtJ
        VUlmYzZLM3lTKzEzci85WEdmOUNvYlNsbXF5cEdRM2M3aHBLTnVOSk9raDR1Q0VX
        OU16QjBsOVlLUDMwb3ZPWnN3VFI0MVlhQktOblZxUW1lbHM1dFFURjJZMVo0ZWV2
        aXAxRFhEcld3TnFoeVo2M2RSdkNsTUY0c01hTE5aRGx0ZzMxZWxmYXovRnZwcDZx
        b0t2MWJDMmU4ekt2b011VTlaZVc4MmljaEEvalMrU21DOU5EWjFoNWZ2S3FZZDRw
        SEVZQWZEWXpOOVpxamFVelRXQkoxbUU1Uy85dk9ZRFh5OTNmbk83c1ZXV1VQWVZo
        cEhQTmJMei9Jc2l0d1hWS1pua1NjVTNvMFNnQ05zS2lLUHE2Q3hiMW1VYXEyMWtM
        bmg2b0J2Q2xGMkZIN2RoTC9ZZ1dVTFRiY1YxVm9acllNWXV3WkUxbWpETXo4NnF3
        ZzNydXdmcU5uWHdtbTQwWTM4bFFtMmdLZ0Rab2tuYnpRTE8wRXhicmV0VVR6dzlh
        SVJxSExWSFZFZ0QzaGJqL1JiR1E3R0Q2cnh0cC9CTkhVa090OVpnRW1ZNVN4LzNo
        UnVyVmRRMWdncmk2OFBEVUlJdWg2ZjAyMHVobkQyZExNa3hkVEkyTWNoT01jRnF3
        TG1wUnVBdkZrS3RVdzRFc0orTXRTZnltUldlVjN5UVFveldRVWp4Q0JxdUI3eWo5
        QVAySEFMSUJnaytVUWh3alhjZlgyYmtZV2hBTDlkQWFUaHpCS0NVN3ZFLzRGY3Jt
        NlNVelV2R3BPU2hoNjlGeVY0cmFRVTFrV0xrNnY5MEg4d202U1dZNGY3T0tvQ0JD
        amd4M2Eza0lCdHR6a0JDSnZRaTMrSS9EMmZ4NlhHMCtrZEh5RTVXYlZrZ2VvRTN0
        b2s5OGhMbEwzcCs3R2hhUVJGc3RZREZlempNVjQvMlpsT0pTbmxlTVhGU2IxTUJr
        YmxkSy9HVmk4aEhkU2FmdjRocU5wZTJqd3VvL24rOS8ydXFHVk81Z3ZEUjJtdmUv
        bE03VWRGUGR4T0RxVzRVeWRJczNzbytOd2lMNlRPNm5jWmRyQ2lJak5UNXlhYm53
        NTFFbndlTHAzU1M1dmdSSmlIL08rREoyK1dnY0lqa3FycFVVbExaLzl0dHJGWVhk
        TzhGWXlsQ0N2bGMzd3g4N0JSdGlXaUY2alp2cXpkNW9qaWNoQkpWSlYrUmU5SDFN
        d1c0SUJUUi9MaHVrRm54c3crSWtqN3JSVTRjRUV1ZVZnc3hudHV3cU1uY0d2LzAx
        b3JiQ0g5akQ3UjNLUmcxU214bWlxMUhEWjYwVUNPVkJrQXV5MWN1U01Nd0dtblo2
        eDgrRE1MajVCekN2ZU5YazJSdkthZFNBOTI1YllCVUQzWTAzTDYrWE4yS09oUlN6
        ZzRKNUN3eG1HazhiN0g0R1d2K3dtbHBPdzkyNHZNQW5DRVo5cnJ4KzZRbHIrVDNJ
        TE5zb3d1MzY1YUlPQlAwU2F1ckFEZ2lhVUsxYy9oemNicmpZMTEyOURKb0hiZwpi
        RUI0YVhPblRRdTN6RVJJejBKa2dVQ0xxUi8wMEwvS1BWVUhtRG9saFlFCi0tLSBV
        WjltR2pUcmxZVjlOUWJIYjJpUlJaUDNuR3pXeUZYbWRQTmc3cXY2d2NVChLCwCQP
        H24ZAp1ZgMopRkmopnnHCwIIlYeJk28NVrJH46rQNoPBxcbPmrP90iS6o6z2W1Zl
        LaJUolALxuGjZes=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T11:29:45Z"
  mac: ENC[AES256_GCM,data:Cz06ZxDoscgAecKTxf52yBJWuzWVkPWg3XqhoFO5IBPcNPjaxJLeY3Hm5fjWUqHocESqm5wE/GYnalMKIkoaIiCum2mR6UWKBd9yOsvLw+DSnhpKFXGAYaNwKT4GJaMZa2i+ov2WpYa6PgHNtLxrwzZ7XiPhK3HFl2o23EXpzAs=,iv:Jr8q3R6kSegOUxWstySI8xxatdQUBPm7DN0VclqcHdI=,tag:LBvzNprbdunhdIVahMcHWA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
