---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./snapshotpolicy.yaml
  - ./snapshotschedule.yaml
  - ./restore.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: unmonitarr-webhook-handler
    files:
      - webhook_handler.py=./webhook_handler.py
generatorOptions:
  disableNameSuffixHash: true
