apiVersion: v1
kind: Secret
metadata:
  name: unmonitarr-secret
stringData:
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:W8uJeExTcbwE61mzQJFv2y/FaUd+LcS6z+U4XwuTfrE=,iv:NnQzKsPmcH2OwsN7zxcsuR5LVS3MQP3yFfKa3795Pzk=,tag:jC/LV44athdBw7ICtiJ2FQ==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:LRbW5nBtiaE1cSBxbVa4nYXnTCEVPBG+G/U3NhvDVH0=,iv:cPB8a4aDgZ4Wp2Qoabh4nf4x9Zh/oQ8vBToqJlnf0fU=,tag:GndLyTXXnqYvBbOplYAr2A==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:KlPtJKKnDrQ79L9ODYI26lnA+7WGbTH4/frj/IMWqeU=,iv:mRczkz1dMiLfozKTFgcFRMx4Tf40mKPTqJp7JPW9ZkI=,tag:4Lwfm7DBT3shgQfwsHlWfg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:JdFlbZDCkUaHdaSKR3SJwA==,iv:qj0AxEuvuzYRNrUCnRO3yKsQoCb0FEfrlAcncj/cYPc=,tag:+KWAQlqXaYJYKI6YfRTrVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDhWckVzVDMr
        QnpnY2FRUFlQT3l1S2Uyalg1UUtrdEVpMjR4ekhkTFNqSEdnN3ZoY1A1dnU4bllt
        UFBSZkpNMjBZK0RJRzJWN296Q3pJbzlLRnhZU1FlWHI0cUdHTVU1RC9xMmU5dlNq
        Tzg1Tys3VTB4d3VSRDAvaGh3TGMrTnV0eFJqb2R4ZTUwVzdYYVMrSUJpT2ZFczhF
        cFNUNDNBcGhnQ2xXNXc1MjF4WmdyVnplQzdhQTBxVVVud0RKSmdqekNIZ3lhOEhN
        VzNzUTRiQytxemJIL3lZdHhuNU9LdXhQRm1mVFF1OGFFVXdSbnViN3JwdzBsUSto
        MGNLWGZVTnRnL21HRGtFL05IYXFNbmlKWnFva0xQUUkwS1ZLbWFncFZhODRIY1p0
        aU1NczQxdGw5Qmo5anNYOFY3SDdBV0lEeE5lOXQxalhqVXhXWjhQNC9ESU1CZGRx
        SmI5YUlSbE14VzJXeXlOait2RkxWbXRHL0Q4L2dvQzFJb0UySVpJNlhyUmxFaTdl
        MHdPelBkVWpBNVVrUFptbXU2bm5jcHJubXk0enFaeVJjeTBKR1hJNjVyVi92YTlp
        ZFhtWmt6Qi8xamdUWE1GTk5IZWZOV1M2VGFDc1hNSmNydzU4QXRwKzdHOE1LREt0
        RmpKcmNSNys4K1d6dWdkZUp6U2lEZ3NQQlc2QkVCT05vcjl6SisxYXByRzFjdTlO
        NG1nYndLeUFEKzcxSWJMOGdOSWE2dEtrd1cwWHpqb3o4Zis2SW1sMUtLLzFoUlNZ
        VGNEQjJkQUk3eHozbXA3Y2dwc2h3NGpFOWpTNHBISk1zSnN4SnhTUlpmanM3TXlY
        Y0FoWWl1bFFoZjlQNURtdjlDYzRXUnpTSEZMeXdUdTFYN25BYnRkMWg3T1JDd1o5
        SHdHZWV5RmYzU3VmalpxVXZLZzl6aVpaSFNTN3ZsaVlXUTJQK3Y1bUJSZXZCb3E4
        S05YNXN3b2NWSk1RWHp3aDhwSm5qZ2xVeVAyT204cXBuRStPTGwzL0JBTEdsNWND
        c1ZKc3poNTI5ZEVFUys2NmZXWGFyc2NiTEp3R2hyVmRmeW9uYlNZK1JwcDJrUDBv
        aFU2NTRZOXQzV2sySkhkYXhHcDVYYmtSeXZkSEFEVTVjRmcweGkyckFTMmRGNXM0
        Wkg2TnpOYVQ4aDdXaVg5SWtjUEkwc2R3aDJDSis4M0RDT2Rqa2cranB1dGEzNysr
        T3QzZHJWQUN0UG1pb0RNTk9wNE9YZ2xzU2M5Um1PZVdaUGk5eDZFa3hSNVlUczFv
        UHpoV3E5YWFraXJVUzkwdXowUHplM2Ywb3lMbEFxM3plZkJWQTk3NHZUa3MxKzFH
        Y3R5V0JVNXU4emJPUmZubGFhZTRMa0o5S0xxejczdFdKTmZOOWxNVmxramR2Qnkv
        QVpOb1VsbmFzR0t2eEw2MmNnRkRDb0ltRU50YlNLdzFtVU00VWE5Ukx6aFZmNENs
        cW85S3ZNVXhhbnZ5ZDVmMlpQN0pHN3lTdEVZUTNZVzJpQWx0M3hWTGZDOHFYRWFM
        ZnVaQTRNNkpybUtpbCtaak1hL1hueURKanFBcjB5YTM1WU5VVWVCeElVdkFVV3Vu
        NVlZWVhDWUM3YlJJekFIeVc0TzhZWVZZamM1aG1MQlhubUhVeVg4WmxES3hnVnI2
        R3lwc3JIK01ubENuUlQ5M3kzN2dTOStKckRmcmdOY3BEb2cralFJQmdHYmdjOHFW
        NHNBdWx5VnRlQXcxV21GNTJTUUlucHNVU3NrQXBxYUhRVDRvcmpxYy9mS3ZTM3dS
        OGtWRUpUQ0QyNkNXTU1LWHBOZXp4M0tSbFRSbmdGd1FpdHhJSnpNaHhPRmU4OE9T
        Yy9mTEdXOTl4MWFleDFXQzRhWkh1T2pTcHJVVDYwZHhHR2RJMmxqZENwY0EwK2tU
        Q3BBaFprOE9ISDNyeTRZbjZ1QTVVaVVpc3hzOGY2ZER1enNGMzdaNEorcWhDZwpj
        QmVIVDR0Zy9yKzhMUEVCSTNQZU84WkFpZFpGbE1MVHhwSGswWm1GS0NRCi0tLSBt
        R1pPUmdxc3BnWXMrcEw0Y1R0QVJRU3NBaUNNK0ZYcW9iamVRWllyV2o4CrT72yEE
        EpufYSoRqkh1ekZ5VuJDF0hcLIt5RAZaFMdH09Vjyirwy+Bc+2aYR6XlwnxVmk3T
        D54bLSOXQTGpJB8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T19:39:57Z"
  mac: ENC[AES256_GCM,data:OTO4OKoNf2Yhz6EE8a3PgsSTkHgArNXCSYHkfryE4onROXpyPpqzAt6uhz3QWtaXUVf2FRjei5XDoStw2U7iB9j0HtjSIn/NC73IDnaHdN9OpNXLH3WzS+mc1K6b43OXCaA07gdgAJ8p1KOgPEL8mZgc7dJh2Kg8IdPnRg3VK3g=,iv:dwWnygEGI392V6SlGb2P/oQ4Qv2B9AnGiRPEr9r6vls=,tag:P1d8pWuBVArgmEzVFlariw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
