apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:85zFUpVsyLsMi9wj,iv:+6HtsaMeEJ249SQFeohkoZiz2tRt3ZX25iuBXT14yU8=,tag:TzZQ28X3NTI5rERg7jW3Xw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEtmYVVuYXR3
        Um5iWmxmRndrWHlFbEg5Z1MxRDFIVDlJQ2RtN0hkZlJ6K1piSHM5UWlCSGw0VnlM
        bzBwU3ZwY3AvUnlsM0ZiSUkxdWsvU3lnRHppeGVTLzlQMXdDMERMVVF0RnV5cFBY
        dzZiNFk0YytCM0J5T0ZUYnpjeHcvM0FyTzhYYkVPTTE4dGtSRVNRWWUyZnBad096
        MVlacU8rekJTMy93bE9HaWpSRCtpd3hLaXdCL2JMOFA1ZzVDNldmclNZWS9qUks4
        V3JCNnNUN1U3RWFCNHY2Q21XQUNPb2JxdEhpdEkzcUtIWlNDYng3U0R2Y0xOZmpD
        aDJXeEdqT1hsZ1RHYlZjaTV0SnZKbSs3eDhsaUFEZHBqWmRlbEJjbFlTa2QxazdF
        aUdVQXJDSDBOVjBPNTdMWHBoUWhldktOOGQ0WFhEZy9pUkFQbkNBV2hQMEdWZ1Jn
        bTBHTTdPT0wycit0SVVYb1pob25EVFlxL0c2VEx6dmtCeHg1aHpXckx4T1J4dE5i
        dWxFQkxWYUFXT1ZlbmthQ2RTTDVvV2Rja3dZQUtpanZSNEdrTnZDTHFNNXBUSFA2
        cEhWR0k3NXhHVFFVa0s3VTRTNlZiUSt5Rk04N2ZSQkRlS0d0T2loNlhuUUdMWCti
        TU1TcUlweEp2NGJ1OEZsQlk2UkY3SzhaZExPWG95U3hlTEQwQWVhVnhPZHFadStH
        ZUF0K0trZ2NXRDVOSFFLeW5Gd2ZOekNQTWpadjFnWGpBWS9uWmlUVVEwenh0c2V5
        NlZUcVNLNlRSems0bWc2NU8zbGhSYm83dEM2TTBQckR0cFZENjFtKzllS0YwcnRy
        bGJkZXc2NzlZUXJ4cThJTkZibFZXTmxlcHVUeFdkRTNORS9EWm90NEVSODRPYTdN
        TEMyb2hDbFpESitocVowMWNlcWthWW41Y2NiQVpxV0ZGbUYzTm4wbno0SmpLSjQw
        TXdkOG9yOUovRzZRWEdaa0JnNzBwL3dHSTRkNm1NRU9NRVRLL094dFpDS281ekJ1
        ZXFrWkpyMHVSVUxBZTdPY3JnWWg2Z1c5RlMzd2xSZXVtU2o1bzZEbS9YdW5pd0RU
        eTlIaml0a2crUGZtRUtpWHVyN00rdGExeExpVVFUUnRJdW9JU3F6SEhraVB6V2Jp
        TFZObmNhOWEzM1BsOEkzWHFVbEhzMFRVM1JLQTJFUXorZU10c3Uxa3dhSVk3RFV2
        ZWJUanMzdWRwakcxckFzMlRCd1lZWFdhZCt1Q0RHNHNjcVl3V2tSRi9UQ2cvR05p
        Wi9QOWlZdThyY0dhOS9YSCt2aWY3QUJGUzVTanFJOHg3bGEwcURiR1J5Zm90c0JR
        NEIyaWhudjRCbXpxMzRCRTlWY3ZSQVNac3BQNlZwRk1ncm5WUGRoM0M2ZEhZVXRw
        SzhNOE9RdDc0eDFlSWNhNEEyem1Kb1hkVEQzcHBzZjJpM1FLb1YvNDZtV3kwQ3FB
        S0wzTXZ2WFZtRldFU20vTXFudkdoSWZaM1p6c08yRURCN09WRlZPOTQwUzRjK2dD
        N092QkV1N3JmN1Y5aWdkOHo3NmNVSHF2ZnZORGNQN01pc0VTbGtRdWcvcS9nc3dV
        aVFuVk1seVVNcnIzWGpFaXQyMzd0bmpsZ1ZJMDdLZXNwZXhjYmZIMHh3d1UvUFI1
        aVI0cTZXcFF1aEg4MVR6ejFWMzdSby9WKzBZaFAwbStxV2F1QVdCdytTNFd3YStG
        eFJUR25UYmdtdkRYSHdRbzFNTXhlQTlFUnRtQm5HYXRlS2FtOUU5NC9BWUdFZ2Fz
        dGZldkF3RHpLanBkcnBkN2dVaEZGblFzRFNkbjVBbGxEaW5wa296Z1dHUXFHSWV6
        QmJUQmd1Y05MczRCcHVmNTMyaDJUV3Z5VUp2R1BqR1FDTW5NaWpRNEtpNVFpelEv
        cjlhVTh0eUFCczVsQzRmbFFZUXYyWUMrRzFKUHBSTVZBZFFiYTh3Zm44WFpkQQpm
        b09ZNFVQbGFwZlpmQVdhQ3NlKzlGWEFrSWluWVBuZ3V1RUR2QzN6dit3Ci0tLSB5
        S2VNWldHSjdxVjBrUURpdmtNVnpLNzFnT3FISVVDUUNZd0FBRnpRckZzCln95eWU
        dhGMMMSZtnYi99r59HmKwKTXCTMv13x8eRYCPAdhcJGtKvHRwuT3I3OFIuY+FVJz
        10gCkAa3z4Wxlok=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T10:13:46Z"
  mac: ENC[AES256_GCM,data:3r4mAGkgmy2fibF8wh2ecSLQQ7IOKQ0X+eFp145Wdneu2JqyLedOEK6DMRXaGCfYe/Q70RJo5fO20R1NW4hHDOSoueqOz3walRAOAjcmyUYOdqavmU/P/ucN8Bw/L9OuYwadWP8RZ45RRLPoms5DgLRx+GnkKBClCzjvLfxjOy8=,iv:6Sx2P3vhh0QdYGImGQum/2OzLxsLv26Z11FHAm5C214=,tag:d71bfUSYL7jRPMhe8wsGwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
