---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kavita
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kavita
      namespace: kavita
  interval: 1h
  path: ./kubernetes/apps/kavita/kavita/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kavita
  wait: true
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
