apiVersion: v1
kind: Secret
metadata:
  name: iceagent-ghcr
  namespace: iceagent
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:VKcUgCBTTgJM7/dm6SpTSBdvqRVWua/711lMGqc8kQxe4Ty2n/7nGSFwcNiFwhu3MqgsSDCJrE7PPYOD7SSURUWuu1+Zh5is7NJ2Mtx9tNDD8AIsO8aC8cWAQRHJeo/oaZ2PyA8FmP2qyhX94frToxWQg7yzpLAqcbB4r8QHkBIuPO6RmIMLHZDp/rXe/FN3,iv:sz/ckB1m88gRIRXypLCC53yGQocyKTlY34ltP6Ru4hA=,tag:xHvKJOB2tqlYcWTDO2VTXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhwM1p2Z3FJ
        Tk1SSnQyQkE1c3B0QTNORFhNYU9PNktxSW1TUVYyYm05ekFYRzNDdHMvWm9Ld00x
        SXIyR3QyQllDWGwrZkgrMnNhWlY5SlRZaWNZRXhPUVhEd0djd1FBMjlta3l6NG9o
        Q0p2QW4ycWRrdzhqTnFuRFNma3pjTmxQczVqV1liV3lReVY2OWFTUy9TeGwxZVJ4
        MllYSDFXUTMzRCtvL1NSQUp2dWUrRTE3MkpaQUQzaEYvVm5Cd3FNK0dzZFpNd1lq
        c2M1TmltT1NFWm10QVJVa01QQytjY0Z1NHJuNFlObnV3SmlJcUN4NFhidFV3Z3FV
        VHE1UkxyTmxNTk91dndmdWx2V2FSdUhDUTY3dHF6RFA5UnIxSEVzVnpuRFhUWjBh
        SDlLaGJ2Qi9KVEp3WFFvbXlKK2F2OWk4V3VoSFZoL0hHT0xRUWZxd3VSaWFxVitO
        dVVXU3NmSEdvY1BoRDlPZWUxdktYOU5PNU55VHZtMlhiMFVlWFR4cDhObTRqRkpC
        ZU83Q3BwTzluUnhmU3lnbzdpeUJZRVNTZDNacEVUcytyT2hwRmxEOGY2VjdRTVJL
        R1ozaXZ1c0lMdElGOUYwdTN3VHFZcERQWlNOWUxQaHNnZXB5dTc1dDl0cWk5VlZq
        eWpIRDlqN3R1aUt3QVJWdGV2WlFpSkF1OHp3Ti9IMHlUZVZQUWdWR0wvWnNXRlpS
        Sm9SVXI5aVByQ2lGZUVlc3REcXJrc1RNY2RjMS9qSFNtVWVvZ2EvR1V4ZU5mU1Bx
        V0djRmRqc3QwLzA3QTcvZG1iS1pLSDR4VWNva3dXOEg1LzBuRWQ5ZUVoMEUvZU1C
        RlVWelc1L3NHbWJWTUdGcDZROVZqRDB2VnNkcTFIb1ZGcFhSQkdHS3o5Y2xRVDl1
        Y1BsQ0MxTnlYTFNiNy94eEtxdGRELzRmWkxBRlQvekpMZHM1NHkzRGM0VXd0c2pK
        VUtxUmJXcVFZb0ErV0xoUGp1TFJESmxrUU9XYnZMTCtFTGNNdWNzSndTZTIrRGU5
        bGZTNCtIbExyS2NzMXZKcDZTUXN0cHJlZ3p6RUlzNGtIa1MveXRVSVZFRk1Jbmxo
        Y2ZKSFFyWnZVSXZRSXBZSWM5WXZRTVExQkpFZ1JuZ3pqNnNkckhYK3lITW5yU2c1
        Nmp1M21Va0FPQXY4VWkwUnZNYU8vSTBsT0hGckFsMVZHMG84U2g2aHdpNmlHMTJU
        V0Nzd3RRUTZ1YWRrcTZjdXdIOTBsRFAyV0tyS0VqdnNjL3c4L28xN2g0L2w2WW0y
        b3VLN21nZTM3QzVuWW9NUEZRbVlUZUlIMC9lRjB2TFB0T1pRaEo2bFhnY0NWRDJR
        cGI4WVJXV1dVQndnNVl2TUM2eVNBeEhyQ05BUkkzT2RzRmp0QVFuWE9VNU1JNWtp
        SGNkcnpRd0Uva0VwWVBpWGl0SGpzZm9uOXE2Nllkd2lUZHVYMHVjMmx3SzdJL1dz
        akhGZyt1c0ZnMWltSjdUcXpsSURhMU5xRmtteU1raWdlL2loRVNDSFFZQlMzZjRk
        T0phTFBTQkpvM1pyNWlFMzR5bUFuQUVLRFJzQStqT3RNZEVDK3ZlZmd3RDJhVmxi
        WG5WbnlKYUVHZU9Zb2VqbFVmLzE4aWhUem9XdHBvNXliK2VOUUdHcHkzZFFaekJE
        dGswZHlWeUxXdWJYTGpXdTBXeHoyWFFqaTF1VXQzTk80cmdWV0FCNTFrWTZaRkZ2
        YXpOTldEOGNUK011RTdndDh1Q01SUTgzYytCaFhQeENGbFp3UDczclBSVjBWQ1dK
        alByYXdkYWhNNG5JcGtsK2lCRmR6QVVvbnhlZTZGaTBkU1l3UDE5QUpjcDFNWWZ2
        dHNIb3ViSWFTYUFjVWRZSER0SStJN2ZZYlNxMWt5KzFEeWFwSHAxSldBenV4cUtR
        SHcwMC8ybzFCRTYxbitrWnBTNFZVVzhRUS8yVDFRcEpQc3dHaFhmaHN5NElGdwpq
        VU5qTHZvd2JtS0RnZG1IaWltVmdDR3ZsNTlqdVY2akF1VXN4b1NDallRCi0tLSB1
        azRUUk5ISVprOC9pTGR0cmFFaHB1OXlMRGxRdnJMMUR6SHE5REJhUy9vCptr7xno
        scq5xRRo5UllulEK3yAKKaQrIBBA3gZ07TxfGPkaO8C0sLYK42vkt8J+XEBxe2gO
        Ukzhnwg4avPdGpU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T14:54:27Z"
  mac: ENC[AES256_GCM,data:MeBQNLw0kJ40WLEmqBPe7C97DfdhSA3+ktaXJZA4x8Vf6aB7OFbuSm5GsjNwDhCkpCmd9KxJYO+USW8MUu6wNLrWWt+I51D4NdftOMj3HK7G5iVhFi/shHtitaHTuhg8uZdDlqDYob9SR9kLIs3LDgdXV74yJ/z9FEQIkOutcfw=,iv:K4Yk3YuDAmPtInwhiEJs5IiFknGh5AJnDL5ICYrH56c=,tag:HYw65bF6heupL/AGgkLhcg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
