apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres-user
  namespace: mealie
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:316jNaXz,iv:5hKcxZeZHSDCs2SDEtzV9y9ugc2KYJpiKLP9QwSAHNE=,tag:2arsnWdclBADxRJYqMQcXQ==,type:str]
  password: ENC[AES256_GCM,data:s/X/HQ8AP2ukMkiAoLpJwhwf6VUs1obCL/ZMFB7SW3o=,iv:kUqMsL/aZmXIQ5GAQ5uHkIYmO1akdLzhb4AgaoktLWI=,tag:N7/THyWRQLyzJbEWAWlnVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE82SnQrd1h1
        MThXakJ6WTNoRjBNWnlPSHFIYkhoeVlUTFZ6MFpiNEhKbEVNb2JKcHRPY0VSeUVn
        UjM0dlFvTzJjbnRPOWlkekFMM3NvQ3oyZ0w1eWpidGxUSVNaZElyRVAySElLRi91
        dFpxdm1kRE44ekZkVUpSNFZDTXhkcmsycUN2SVlSQkdyMmFFa3JMNW5IQVdBa1ps
        ZTFRbWYwejFqajAvRjJ1Tjk1YytlUDI0K2FKTFRFR3czbTVKbURaQjdZS2dBWjd5
        N1lrdjVycURaR0hPR0QzcExady9BVE1ySjhpTGhEWDJtR1VVQVJCQ2RYNEIxTVFS
        K0ZIRHhFdnhKMDFpUHZjUzV4VHZMemRhWUpRSlRudytXSnJkZ3MzSGVFczdHbTRa
        aTdxZlRmZW10RW16N0lobTdiWmdPMXFsU3hyOXFKOTgzRm5HWnRiclk0T0V4bW1l
        VEFrYlQwWmRjaHhaWU9ZNjYybG1CZHhUMzdRZHdZRncvc2RkQWxFVzBpdjZvOTg2
        WTJtaHV2Wkx6YkduOGpKd2cwNVlaejdWUVFJbFhnUUdCWHR3RmZPc0RlK0tYZmlK
        OWY1QmliVk5vUnlJRm4zVHhkc1pvd1pYZTVKRUQ0UDRvVmwzSFhjWUxvYTRVYXFJ
        UDZkNzZ5SS9yOExvZnVDSWhyeTlzRmpPbzZGV2Z4QmhxaGlPSUhjNUxZWmpZazVv
        c0ZjWUZ1ZTl4aHFQbExWMkJmNnVyNXg5eUNsT0JTTk5uWmt3bkwycUVoRGx2Vks5
        NmozTHc0a01wQjU1L2FnS2I2U0dzRFA4bnhRM2JLa1drRWdwaTJuUFpPa0JKSVhR
        RXZNaW1oekwwdE1QUHdiNkhmVlI3Y1BISnZHT243LzlhRzM5S251NlNvN0Vna25D
        Vk1UV1FWK2FMKzhyYjhQQzIrWGh0UmRBTHZuZGxUUHB3TXZTN3JQeVFxK0ZNdlNN
        VGFVNDloZjdUUjNiOFN4S1pra1M0SUlYdGUrQ1Z3Q0hqd0M3OXl5V3ViaWZFZTRw
        YkZjQmlpZ3BCUFVydlE3YlpnYTkvU2dyZ29JRXk2TFJoK1RvaWVaUWE5czZUR08v
        OGg2VWlzRzlLRUp1MWlTU2dFb1FXRHdNelhmSEpvZ0pQbGVtMForOHFDK1BEOVJq
        ZGI0M3lvREtTR1RaSVA1NUJCeFhqL3FlSU1xMjJKYnppdy9DMDZnV2FMV3hvaHBq
        SDFsMEs5MHg0ME9YYUxtQ0NVbG40WEtsTHE0cTdIY0xZVXlNbnN1YisvVmRlZU5D
        cXhFN2tyQjVqaDhnSHh4aE9ZblkzMlpRNjFaZDNmM1lLUk5wK0FkWmJheW1oOGJv
        U1ZvdllDNm1BSERtbW9mV3dnZ2VDd00yTllSVGhPNjU1bHF3alMwTmpnYTl2Qk5Y
        SVBmbVIyVVczdGJCZWIycStXRS96S2pLVTVVNHZOdWJqdWRGd0Q1MitBNUFOa0ky
        UGk2dnNBVGNqcUg2ang4bmhVTU1NYzZreU51TE44YWJrMEtnWnZlemZlNktKamFN
        azhmR1FRR0ZlQVpBYWtDM2ZSTHFHSURteUZubE1LSGJUTFFaK2p0M1lqZG1raXUy
        YlRPZjUyNWZPanRZVEZ1SzBIOWhnVjJRRUF1aVBBbXpoVkVNcHZrU0p2UzJCdnh5
        ZTgyakRpTEhkbklPV1RqOVlYOTc2a0lnc1BkUngvZ2VIQVYySEpzeEhtK3lYbUVk
        L3JpZVF0VWVycUhDa2RzOHU5MDc4Q0JjNitkYkRrZlBESVhSQyszSlZqS3FmeHAx
        cFdLdDdPa3hFS0haWkV0OGlCalZxNHh3aXRFZm1qOGF2b2FMRFBuVmZSdnhiUm94
        cE1yVmhON01UVGhwNWtlM2lCc2p4bkRwSzgzY2l4TTVwMFdYa2l0UWxGYXk0UXc2
        TUd2NDJqR2sxSUJheGt5Z0Jyb1BrYTJWU3pUTGdiQzNRZXA2anBGQVRvTzZNUQpE
        RklHZ0ZsZExvcTNla2RGck9ndVUxajBPYytwWkowQ0l4S2Z3R3lrV0s0Ci0tLSA3
        dlZHNmlIM0N3czBjSTE5NGZYN0RkMG9ueURNWE1Oc2NGSzRZR0tBNWhVCl259zCr
        uuq+kZ21LACsYcuLcUB24r0Gnmxs8PhmqJ7mbiElaX4OQ+crLx9UuS83620LQaCT
        QJASj7fsag95IKg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T13:08:52Z"
  mac: ENC[AES256_GCM,data:ililFNzXwa2Zn4jkLe9hADVBJkH/otzGqvPdvxbOeGCA7v1G+jldFfdKvYuYqMxR0/Tr0FZZjoBBZEkB6JsQBFWzfhoHqPjU7IBOVaHFR1mAMSeQlHTal1sWrLOT++AkrAS4GN4IH3o0Oh9JrHN3ZgoV5TUY97lwEC49SCOwROM=,iv:dWwu8kJYba1G9pCD8zhtLqx4w93VPildZW+S2fL8i94=,tag:rHYVDWKArGa7hHibEKbI6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres-s3-creds
  namespace: mealie
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:JSOgj31ckbMC/ndpCTV+DpAtzHuzUkGjcA==,iv:k0xYsc81mFWoCC/zTi2iouOpabmUu6IKYUIcmN/1LBc=,tag:rj9RvZODbL56zSWUnSzX4g==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:yFR7W4HMG35PcLLrCUMvdmVXmz1tHTYjmuzJLTnMFw==,iv:oUWUckHtLDFy12CbK9DCvy6A0Tnr85vofQCJJQ0edR4=,tag:H7mq9qXNrLK3W/plIMVvfg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE82SnQrd1h1
        MThXakJ6WTNoRjBNWnlPSHFIYkhoeVlUTFZ6MFpiNEhKbEVNb2JKcHRPY0VSeUVn
        UjM0dlFvTzJjbnRPOWlkekFMM3NvQ3oyZ0w1eWpidGxUSVNaZElyRVAySElLRi91
        dFpxdm1kRE44ekZkVUpSNFZDTXhkcmsycUN2SVlSQkdyMmFFa3JMNW5IQVdBa1ps
        ZTFRbWYwejFqajAvRjJ1Tjk1YytlUDI0K2FKTFRFR3czbTVKbURaQjdZS2dBWjd5
        N1lrdjVycURaR0hPR0QzcExady9BVE1ySjhpTGhEWDJtR1VVQVJCQ2RYNEIxTVFS
        K0ZIRHhFdnhKMDFpUHZjUzV4VHZMemRhWUpRSlRudytXSnJkZ3MzSGVFczdHbTRa
        aTdxZlRmZW10RW16N0lobTdiWmdPMXFsU3hyOXFKOTgzRm5HWnRiclk0T0V4bW1l
        VEFrYlQwWmRjaHhaWU9ZNjYybG1CZHhUMzdRZHdZRncvc2RkQWxFVzBpdjZvOTg2
        WTJtaHV2Wkx6YkduOGpKd2cwNVlaejdWUVFJbFhnUUdCWHR3RmZPc0RlK0tYZmlK
        OWY1QmliVk5vUnlJRm4zVHhkc1pvd1pYZTVKRUQ0UDRvVmwzSFhjWUxvYTRVYXFJ
        UDZkNzZ5SS9yOExvZnVDSWhyeTlzRmpPbzZGV2Z4QmhxaGlPSUhjNUxZWmpZazVv
        c0ZjWUZ1ZTl4aHFQbExWMkJmNnVyNXg5eUNsT0JTTk5uWmt3bkwycUVoRGx2Vks5
        NmozTHc0a01wQjU1L2FnS2I2U0dzRFA4bnhRM2JLa1drRWdwaTJuUFpPa0JKSVhR
        RXZNaW1oekwwdE1QUHdiNkhmVlI3Y1BISnZHT243LzlhRzM5S251NlNvN0Vna25D
        Vk1UV1FWK2FMKzhyYjhQQzIrWGh0UmRBTHZuZGxUUHB3TXZTN3JQeVFxK0ZNdlNN
        VGFVNDloZjdUUjNiOFN4S1pra1M0SUlYdGUrQ1Z3Q0hqd0M3OXl5V3ViaWZFZTRw
        YkZjQmlpZ3BCUFVydlE3YlpnYTkvU2dyZ29JRXk2TFJoK1RvaWVaUWE5czZUR08v
        OGg2VWlzRzlLRUp1MWlTU2dFb1FXRHdNelhmSEpvZ0pQbGVtMForOHFDK1BEOVJq
        ZGI0M3lvREtTR1RaSVA1NUJCeFhqL3FlSU1xMjJKYnppdy9DMDZnV2FMV3hvaHBq
        SDFsMEs5MHg0ME9YYUxtQ0NVbG40WEtsTHE0cTdIY0xZVXlNbnN1YisvVmRlZU5D
        cXhFN2tyQjVqaDhnSHh4aE9ZblkzMlpRNjFaZDNmM1lLUk5wK0FkWmJheW1oOGJv
        U1ZvdllDNm1BSERtbW9mV3dnZ2VDd00yTllSVGhPNjU1bHF3alMwTmpnYTl2Qk5Y
        SVBmbVIyVVczdGJCZWIycStXRS96S2pLVTVVNHZOdWJqdWRGd0Q1MitBNUFOa0ky
        UGk2dnNBVGNqcUg2ang4bmhVTU1NYzZreU51TE44YWJrMEtnWnZlemZlNktKamFN
        azhmR1FRR0ZlQVpBYWtDM2ZSTHFHSURteUZubE1LSGJUTFFaK2p0M1lqZG1raXUy
        YlRPZjUyNWZPanRZVEZ1SzBIOWhnVjJRRUF1aVBBbXpoVkVNcHZrU0p2UzJCdnh5
        ZTgyakRpTEhkbklPV1RqOVlYOTc2a0lnc1BkUngvZ2VIQVYySEpzeEhtK3lYbUVk
        L3JpZVF0VWVycUhDa2RzOHU5MDc4Q0JjNitkYkRrZlBESVhSQyszSlZqS3FmeHAx
        cFdLdDdPa3hFS0haWkV0OGlCalZxNHh3aXRFZm1qOGF2b2FMRFBuVmZSdnhiUm94
        cE1yVmhON01UVGhwNWtlM2lCc2p4bkRwSzgzY2l4TTVwMFdYa2l0UWxGYXk0UXc2
        TUd2NDJqR2sxSUJheGt5Z0Jyb1BrYTJWU3pUTGdiQzNRZXA2anBGQVRvTzZNUQpE
        RklHZ0ZsZExvcTNla2RGck9ndVUxajBPYytwWkowQ0l4S2Z3R3lrV0s0Ci0tLSA3
        dlZHNmlIM0N3czBjSTE5NGZYN0RkMG9ueURNWE1Oc2NGSzRZR0tBNWhVCl259zCr
        uuq+kZ21LACsYcuLcUB24r0Gnmxs8PhmqJ7mbiElaX4OQ+crLx9UuS83620LQaCT
        QJASj7fsag95IKg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T13:08:52Z"
  mac: ENC[AES256_GCM,data:ililFNzXwa2Zn4jkLe9hADVBJkH/otzGqvPdvxbOeGCA7v1G+jldFfdKvYuYqMxR0/Tr0FZZjoBBZEkB6JsQBFWzfhoHqPjU7IBOVaHFR1mAMSeQlHTal1sWrLOT++AkrAS4GN4IH3o0Oh9JrHN3ZgoV5TUY97lwEC49SCOwROM=,iv:dWwu8kJYba1G9pCD8zhtLqx4w93VPildZW+S2fL8i94=,tag:rHYVDWKArGa7hHibEKbI6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-env
  namespace: mealie
stringData:
  ALLOW_SIGNUP: ENC[AES256_GCM,data:4JR10A==,iv:eZeHnxcGgIkdqn3A5prraT0p9SKk+y9dcRsk4NZpxOc=,tag:xNWNufB+u/W/S1Q2EMQqYg==,type:str]
  API_PORT: ENC[AES256_GCM,data:TfKtZQA=,iv:ktusHEdgyAyiRcqibafFko85NKxdKWJllyxttKEISEA=,tag:33YU5DDD5kdzbXo/EcVaEw==,type:str]
  BASE_URL: ""
  DB_ENGINE: ENC[AES256_GCM,data:8gbjsor+P34=,iv:V6VNgvnd/VHotIoJkBBo2Ox0W1HroTqxh6A9vn6Nni8=,tag:EQLbhSCouprNhLwnSdAEnw==,type:str]
  DEFAULT_EMAIL: ""
  DEFAULT_GROUP: ENC[AES256_GCM,data:czjfCA==,iv:0dS+zaqN+5YwHvpUVvP196zLPeDhiqWMsZd/QKX6RJs=,tag:MCG9bVO+HGx4TgOkazclLQ==,type:str]
  MAX_WORKERS: ENC[AES256_GCM,data:7A==,iv:jLgZDVE5e1ucCWkA6gptZriILldpteel0H4T38Q8u4I=,tag:mR0a9U6lFzK65KwpNoA0mQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:rP/ppEDN,iv:kDBOni7+BjBZNm/MBB5d7jpqyoLk92csgD9kbrLjjPI=,tag:0Cb6j2GH39fprAL5Ngn7ZA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:0Vg90tT6U0eMNuzEdd9+1x28vUs9u/Ahq0UbhQCufGw=,iv:j6qr0RSq7dS+Foim2fqFU3aHHHIbSPRztdNrXbufLRw=,tag:LW+bT+Q4B0lnmHMERmkujA==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:or9Y/g==,iv:shCeTzYS2MKzgU+DoyFgZrcyBKq5NermmccDMPvlv4o=,tag:HMpNyR3PGSVQkONV6J1NKA==,type:str]
  POSTGRES_SERVER: ENC[AES256_GCM,data:ilDeyWdgilZQoURIjBrHjvS7,iv:ZzK4bHnfWSUuCyausGBPkt9Kd9atBeoih/LIM9cz0Qg=,tag:6/gKNyIjBWQnVqfpqfQ82A==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:Cv4xMAn0,iv:2E7HyR2INqYZd6BEMdo36EvasHxC2J8mkwTHVAUrGr8=,tag:shokx3vfuqSIFu3Pa/4rAw==,type:str]
  SECURITY_MAX_LOGIN_ATTEMPTS: ENC[AES256_GCM,data:ZQ==,iv:nBrGgHzFO4EHzt6lWSTr3yJqmtK8YK4sJiff6m6sH+s=,tag:55XSr7Obohu1QBWjkVyy+Q==,type:str]
  SECURITY_USER_LOCKOUT_TIME: ENC[AES256_GCM,data:oC4=,iv:M1fUO5/7Hsl/h4zinayxmJuh008t2X8GtUSQNpZXwps=,tag:pf/+EX7Fo6eFQU2nBOZCew==,type:str]
  TOKEN_TIME: ENC[AES256_GCM,data:ykM=,iv:M80nU3gJQrYSFaqMzB8akBe7ePRZ/UcI8G94IiVIT9M=,tag:xslocM6vkhVteiSOaXPqjg==,type:str]
  WEB_CONCURRENCY: ENC[AES256_GCM,data:GA==,iv:9J+NwhUBHeDn3ahgBzWhPgHnJyUlojpcts5AUBC94BM=,tag:pY/Q8VAbR55IUHnmoFqSuw==,type:str]
  WORKERS_PER_CORE: ENC[AES256_GCM,data:cA==,iv:3SGD/W0fkeATcArvQJ1k3vj7RQtKCmSXU6Q95lGBb0I=,tag:kdcIo6mNYlz29G1B72jUmA==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:y/LEqS20G/qmVQldCPdmasrUP+ALWn4uhqzhlXUSrl9EqNEc4CjK,iv:mx0738WteUUJaGYhfRk8Vv3bRp8K3S+b46kIkiGnUrg=,tag:D7QO3x0E5Tix+TMxms+OyQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE82SnQrd1h1
        MThXakJ6WTNoRjBNWnlPSHFIYkhoeVlUTFZ6MFpiNEhKbEVNb2JKcHRPY0VSeUVn
        UjM0dlFvTzJjbnRPOWlkekFMM3NvQ3oyZ0w1eWpidGxUSVNaZElyRVAySElLRi91
        dFpxdm1kRE44ekZkVUpSNFZDTXhkcmsycUN2SVlSQkdyMmFFa3JMNW5IQVdBa1ps
        ZTFRbWYwejFqajAvRjJ1Tjk1YytlUDI0K2FKTFRFR3czbTVKbURaQjdZS2dBWjd5
        N1lrdjVycURaR0hPR0QzcExady9BVE1ySjhpTGhEWDJtR1VVQVJCQ2RYNEIxTVFS
        K0ZIRHhFdnhKMDFpUHZjUzV4VHZMemRhWUpRSlRudytXSnJkZ3MzSGVFczdHbTRa
        aTdxZlRmZW10RW16N0lobTdiWmdPMXFsU3hyOXFKOTgzRm5HWnRiclk0T0V4bW1l
        VEFrYlQwWmRjaHhaWU9ZNjYybG1CZHhUMzdRZHdZRncvc2RkQWxFVzBpdjZvOTg2
        WTJtaHV2Wkx6YkduOGpKd2cwNVlaejdWUVFJbFhnUUdCWHR3RmZPc0RlK0tYZmlK
        OWY1QmliVk5vUnlJRm4zVHhkc1pvd1pYZTVKRUQ0UDRvVmwzSFhjWUxvYTRVYXFJ
        UDZkNzZ5SS9yOExvZnVDSWhyeTlzRmpPbzZGV2Z4QmhxaGlPSUhjNUxZWmpZazVv
        c0ZjWUZ1ZTl4aHFQbExWMkJmNnVyNXg5eUNsT0JTTk5uWmt3bkwycUVoRGx2Vks5
        NmozTHc0a01wQjU1L2FnS2I2U0dzRFA4bnhRM2JLa1drRWdwaTJuUFpPa0JKSVhR
        RXZNaW1oekwwdE1QUHdiNkhmVlI3Y1BISnZHT243LzlhRzM5S251NlNvN0Vna25D
        Vk1UV1FWK2FMKzhyYjhQQzIrWGh0UmRBTHZuZGxUUHB3TXZTN3JQeVFxK0ZNdlNN
        VGFVNDloZjdUUjNiOFN4S1pra1M0SUlYdGUrQ1Z3Q0hqd0M3OXl5V3ViaWZFZTRw
        YkZjQmlpZ3BCUFVydlE3YlpnYTkvU2dyZ29JRXk2TFJoK1RvaWVaUWE5czZUR08v
        OGg2VWlzRzlLRUp1MWlTU2dFb1FXRHdNelhmSEpvZ0pQbGVtMForOHFDK1BEOVJq
        ZGI0M3lvREtTR1RaSVA1NUJCeFhqL3FlSU1xMjJKYnppdy9DMDZnV2FMV3hvaHBq
        SDFsMEs5MHg0ME9YYUxtQ0NVbG40WEtsTHE0cTdIY0xZVXlNbnN1YisvVmRlZU5D
        cXhFN2tyQjVqaDhnSHh4aE9ZblkzMlpRNjFaZDNmM1lLUk5wK0FkWmJheW1oOGJv
        U1ZvdllDNm1BSERtbW9mV3dnZ2VDd00yTllSVGhPNjU1bHF3alMwTmpnYTl2Qk5Y
        SVBmbVIyVVczdGJCZWIycStXRS96S2pLVTVVNHZOdWJqdWRGd0Q1MitBNUFOa0ky
        UGk2dnNBVGNqcUg2ang4bmhVTU1NYzZreU51TE44YWJrMEtnWnZlemZlNktKamFN
        azhmR1FRR0ZlQVpBYWtDM2ZSTHFHSURteUZubE1LSGJUTFFaK2p0M1lqZG1raXUy
        YlRPZjUyNWZPanRZVEZ1SzBIOWhnVjJRRUF1aVBBbXpoVkVNcHZrU0p2UzJCdnh5
        ZTgyakRpTEhkbklPV1RqOVlYOTc2a0lnc1BkUngvZ2VIQVYySEpzeEhtK3lYbUVk
        L3JpZVF0VWVycUhDa2RzOHU5MDc4Q0JjNitkYkRrZlBESVhSQyszSlZqS3FmeHAx
        cFdLdDdPa3hFS0haWkV0OGlCalZxNHh3aXRFZm1qOGF2b2FMRFBuVmZSdnhiUm94
        cE1yVmhON01UVGhwNWtlM2lCc2p4bkRwSzgzY2l4TTVwMFdYa2l0UWxGYXk0UXc2
        TUd2NDJqR2sxSUJheGt5Z0Jyb1BrYTJWU3pUTGdiQzNRZXA2anBGQVRvTzZNUQpE
        RklHZ0ZsZExvcTNla2RGck9ndVUxajBPYytwWkowQ0l4S2Z3R3lrV0s0Ci0tLSA3
        dlZHNmlIM0N3czBjSTE5NGZYN0RkMG9ueURNWE1Oc2NGSzRZR0tBNWhVCl259zCr
        uuq+kZ21LACsYcuLcUB24r0Gnmxs8PhmqJ7mbiElaX4OQ+crLx9UuS83620LQaCT
        QJASj7fsag95IKg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T13:08:52Z"
  mac: ENC[AES256_GCM,data:ililFNzXwa2Zn4jkLe9hADVBJkH/otzGqvPdvxbOeGCA7v1G+jldFfdKvYuYqMxR0/Tr0FZZjoBBZEkB6JsQBFWzfhoHqPjU7IBOVaHFR1mAMSeQlHTal1sWrLOT++AkrAS4GN4IH3o0Oh9JrHN3ZgoV5TUY97lwEC49SCOwROM=,iv:dWwu8kJYba1G9pCD8zhtLqx4w93VPildZW+S2fL8i94=,tag:rHYVDWKArGa7hHibEKbI6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
