apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ls3YSNxjJ5FONReYHClws6sXrxOX7pgeNmbdUs8TPiKITsQvyGfy10Bo+p6DxDf6DmH+rqU=,iv:47Mg5osnIJnK3wDk7vl/hg4HVvAe+W0RxgXAqP3FkBk=,tag:CwCYTDLp8gwjkUzEr1l8/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFaczRIZGJ1
        S3pIY3VhaTdWVS8zbHdUcXZzakVJVlhpTExab3lMSkhMU0ZGVUZrZDhaTFBOWVB1
        ZlRiUk1SSXZyb0s5cnFod1M2WUozeERQR2lSY3RyZmxkYm9iV2hXbjUxdWk3VllR
        b3V0TWwzamo3WDh5NkFGczc4enFZVXpRL1NxMVV3NExZSDM1K2VpSDJRK1ZhdFdC
        TDFrQVBnYUVBWTNDMzlhais4OHpsNklqT1JaSmErdXRFNlVjM002Uy96d2I3NEo5
        UG9ESlJIc3BrZVN1a0RKb1htckpWaHFpdStrWFJsbUZVRVgxdnBmbk1mQk9pQjBS
        ZERvRkd3Zm1ORzdlVlB5SEhSS0o2SURRN1BSSStZM24rMnpCZDFsZUYydm9rY3Q0
        bGtzUzFyS3diOVZzTGtUc2FualBPQ3F4QWNQakplWnFCMjBPQXNKTURKYVBaS2Uy
        Z1p0NUM0N0FvaEtvbHRjbHgzU1FlZTlFbFBhbGxQUzEwQnk3aXRlR1Q0eDVTaXQz
        Nk5zcTgxL1B2dUJRaDB3bGRlZEFnT2l2dUJIWW95dVBsd3hJYk1pcHZ2NjkyS0Rl
        d2dMNHdVZ09mOUVNWExrUkdMM28wcnhab01GNGtoaDd0NWpZenNiY0pvZENlQ1dF
        UFNQcHlmbEFxWkswY3F1K2VGWmFjMWZUSGJBaGxFaFd2ODVOTXA4cVZwV2lGWktG
        Q2NxRDU4cHU3TktHYTNxUm5pWVNUZjNFenNQb0JBY3NRaGtoQXA3RXpNN2lDNWIr
        amF1Uk9OV3ZiYlc2UGtPVGJsT0dpQUMwMlNrYXVPNVJmd3IzSzZuZ2hpT1ZxT21W
        bnVqMWduRXNvTUF5N01KSUpkMy95UzJseEdQY3VhZWJnNFN1dEFQVnJvY25RSDlZ
        bHE3OFVVNGkzTWpoTDdXUmoyNVliSHRWNlZaQ3ZYaFlxeGF1YlRsdFBjallNWXBE
        T0RVdjdndS9nMTJKTHlIZ2V5SGQ4Wm9vdzV4Wkp4bjJZYmF2QlNSL2RqRlpLOXBt
        RHhvUkY2MTNnRkRjblduNGR5QWQxeGxsQWZFMHhaQy9jZThNbnR1T3dUenBCYi9X
        bWEzZ1JQajlBa2ROME9uWGlyNEVxb1hSQ0o1UFhyR2xscUYzVW45ZDhucERuODJD
        bjFjQ1JFQjV1eDdvRzU2Um5YaXdZemFaYWVjS2RuVFBYRDRXQ1VoV2hmR001bklM
        NmM1Y2FsOEU4NlhnQ2JWMXB3WUVQODRTaVRhRm5iZjJwUXRBWkQ2MVJvVWd1NmZ3
        TWJ5MGNpbGhiclFOM1ZJUGJFeFZxM3E0b0c4N1lCRHllUHNLSy9kRThkNGMrUW52
        dmxWZjZqT0MwRjl1aWhKbGdxV3cyS3RPWk9UakFkRXFDeFlOa3A4VFZaZElnZXV6
        N05nSVplaWx6d3BycjA5M3VuZlh6ek9STFVPS2tYcGJZNjFCOHYyRHJxTWh2ZXB2
        S041OHlQYSs0ZXV4Tm9yampJYkR1aDlaQUNHdnNBTCtDSXl0M2lhYXJjdFNoVWRm
        TlF1eERPdnA2SEVvVDRtTWJyUnlHNmtZeVNkWnpubUkyRWRZVDB0K0s0ejRML0s0
        bGJyei9XMG9RZnNteG14OFp5WUlFcFVTaGN3aUtJRjJmOHZ2QkRKdm9BLytYV1or
        Z2oxWFNibTNtTkdpUWZQMzBUaG1Jd1JpanpGeEVlQmM5VEVDSUxqQnRRd3gyazUw
        WHY1R3U1bm53MjlVUFVUMHdqM2Q5TWRrUWlCeDhwamFDbmRoUTRsTjhDd3pNanFL
        aHdCa0VjQVcxanFtWENDK1c5R0J1MG9zVzI5NFMwMHI3UHlHNjZwZ1J3Qit5QUZQ
        T0ZoT0V2TTBUdmpOczBleWVXZ0sxVWt3bFNlS1lETGlicmFUbFFLdTFNUEtzUHhS
        T3RJcmhKVzJaNHBFNFdnc0NIOFRETUdyeWJjTnZsUEE0eFcxUnJTNUNYeHpldwpZ
        QitRNk9DNEo2aUhCZ01MVE54WTc4b2RpYnFLZ2tUR2ROT1QraHFaV0I4Ci0tLSA5
        M0Mrc3BrUk9TME9acFYyMGJ6OGFVSVNjQ01ITW1KUkV4Z1F4eGhXb2lVCvaZBjzi
        yWJjNYbTYRbGFXGF9Z+qF9rNOhF1Mk2UzIuj2uL93oWYYEtDOnvm1XJTc7SuWYRy
        NzqJqaRLWpVss7c=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T11:29:44Z"
  mac: ENC[AES256_GCM,data:/zQ3XdPaLbmnujLESMXqVnVEdRKgJ4XN2KIdbgcBwxrDCxtQiEg/YKjvUVNeq5urmg2KKLvjPpyQrX9pEexHxQlKnUs2JkgbenWBNpVioyp4umoVgy/5EzVmaxDeMkLY6G5f/0gK/SKjkkwAYhYV+IgRoSZNwX/s5yb4hr/mqXI=,iv:lkgFQT2xZiySejU6tqcL9/oolRcEyBWQDgC2g5pDW5w=,tag:lDpvLrUVT9dG3jdQLSxVPA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
