apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:b48FFoDLexmph6gGrP9admO4DFDr+bmqyzaycHqV7fI=,iv:wP6+8uEeP/v8/CxtW6ldPxqpyfPx6YxTu428Dt7bJbk=,tag:r8XyrfddMQwxF8b6zoJHnw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEdVaExyTzVr
        SlNrZmorVnNXQ3JGVnJvZFp0K0dObEFpa3A0L0Z6SVZGOVNiTFZ4WmJzeiswSnNO
        WVlqU3QwRmFUN08xVWlURGR1L3VkK3hLNmhsYy9KWWpySXBSVXBkenkrWmhyV0FK
        c3hxaHVRanNWek1sY1hDU0VrL3RKNGdGQXo0R2JIM0IxWkJ6TTlkNjA0dEo2d1Zj
        VUxTOVRqbHY4M3R2dUpOcE0rZ2RWQ1hpMldsaHBvTzJCU0dzbnljdmo5SE13dWgz
        QVdta0J5YTFPbUFQZktOYmdQV3pmQmN1VDFiSHNvam9ZdEZlRDhuelIyVHMvTkRs
        VmJTRTRoV1N5SDZsM2llYW9WYjIyQU5BNjJYaXBvUnE0WlYxSjVBYkRmMEZpeWZY
        Tm5FL1ZZblVmYlNaZll4SGZUV201YnY0MWoyNlpUcGpzNUZRaTc1bkxURDUzVHg5
        cXRlcUZJWVBLaXMrM2xESTZ5VDZRZ3JndWNQblYxSS8rNWxEU2pvay9GWk10YnJF
        Z3I2MEFyejNic3hTSlNSS1B4a3FmTTF1dnV1MmtTc3Jqd2pJSDVJNWpzNGhNbnoy
        STgvdXNXYVp6UUM2OWZyK2dFSjlHSUZzUmxBcnQ5aGQ2Q25MRUozQkJZZXp1Vk41
        bWJvckJyVzZQdE5xaFRpajBFVE1mdEZHVkhQR2JiM2s1NUpaaTJST0o5VjF6bWgx
        c21ESXFTbHhvd1h1V1FlWFVmY21CNC85eXArbFhwWjE4RDgyWnB5ZlRmc1lOeGk5
        R0FxQzNjdithclUrWXFuWk83SWVQb21VdG05SDZsTUVYVzlpMFZYOTgyaFRTOUpH
        M0IxRDE1U3FmWWc5eUdOOUcweW5aNkp4ckdsTEUzbFJJdjl0bk0rZDYrcjFYbEpq
        OHFkZmtrVVNOakVZN2wvcGNvZjRpYXFFREIzdTR4ck1ocXRlclRLMnQrck9GaEdN
        TGJDN0kvUmxEU0hmS2xQdE9TY0dGNWdpNWdrS0J0bkJZTGE5cXlQbm01MndDdFFR
        R1VpQ2FjaTA3RmNwZk51THA1blF3T01oTU0xNXErZ3M4TnpwQjlEcWNWV2xUdStH
        M2N6a3hJbG1KeGJxUWVGT1hMM1VYaDdTdCtSNkw4aWFGb3kwWU0zbVAxZjh6d1N4
        aTdaRDBBSTF1amJ6emhwNWNqaTB4TzVRN21jbk5QYnlrMVRiS0dwWUEvbUFBU0pC
        YXpGQU5NaC81dFRUREx0MjlHM0FpenVRM3ZIcnhUcjdwUHZHTDB6Z24xMHczV3BT
        QXFqak1zRGZIRkY4UU0wZkhKREV1cHFWMlVPYUR6TFM4Sm91Yk9pLzdBSCtRUTlS
        UFRkYUJoVXdiV01oRk5SUThjSUZuMVhUeXhLMUJmOFJ0NkRFemk4RzVFaisveTRK
        MmpiZktlTGlXdEUvK2dpQTEvYmtvRUV5a0gyTEFoYlBid2ZJWEdQZlBpTkpIUE1V
        ejJST2V6WVhVeGVsdkJkcWJyS2l0c0w5Tkhrd0oxYy9IVndDT1k5SWdIOWFKUnFK
        dXYvY2pCZk5PdnJkZU5jV0lmWjhUL0NoeExlZXpLVXcvS0t3ai9iTmlwV2dXR1Y0
        L0lKd0FNNnZkUlR3WmYyTUl6NENCdXJ3TXlDT0JVSFJVeWdidzdWcEtyOTZjL2dR
        VWJ2S3hwYWp1QkxvaGt1dDR3dXpiUmpHUEc2ZGhKUGx5NnNqc3U2dU9ZdHpSd2Q2
        ZDJZd2FwL1RTa204aXJ3MUMwdXNZSzl2Tm4vYlBReVd2MUxiNTJlaHV1OUpoWElJ
        WUJ3eEFmbE5KcFVSYXhBaWpZak5kNE5rMUtrejgrNmxIU0pxZzFnMmowRUQ3aWJ6
        MTFmN3lBblIzZUFXeXFWMElCNWIrVmVHQUg4R0dqSTVpZGN5SW14dTZCVkpjTlZz
        dytkRE1udzlKK3YxeG00WHFUaTcxTFBDcEU0bzRyNmFJNkswQnY4YzdBY1dWZwo2
        clU1VEFUaGQ1dit2bjgzK0dyUUpsTjhoeUJwOW5sa2FuZjhLaldhUEhRCi0tLSBS
        bDFJamg1bGhDWk9ZMUM4YU10ZmhrZEIwSGtLUWkxNVpYTWF0RGJNSFQwCsnMPVSk
        /76vmkrpbGCav7jLAMQiM3ALT5u6Z+lkvE7pk+COg3D8hutS+2OLnqHMvCjnxDWw
        19kTFYWX7V01BVg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T19:39:57Z"
  mac: ENC[AES256_GCM,data:4Wb83YVrn+oEVuB503pSz8lvXV5LoJMAti60WcFTYhdW/nGfGFAY3VmJOp95mg4gORF6Gj9N6GiUy19IQrogPeJC7qt+5jyR8XgxKeKAtRy0KoS8rur3V7ND5YWarT891bcp+XY/VuTz9kmacoWMhUqCCpdqS+WBjkLG8IiroR4=,iv:SGlnhiekNiRlDt6a3QL3bJDbOf87+rrPPP2vt+jNZRY=,tag:5Sskhfo4iEeOrbnhjjpSBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
