---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 1h
  values:
    defaultPodOptions:
      dnsConfig:
        nameservers:
          - 172.17.170.211
          - 172.17.0.10
    controllers:
      gatus:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: twinproduction/gatus
              tag: v5.16.0
            env:
              TZ: Europe/Vienna
              CUSTOM_PATH: /config/config.yaml
            probes:
              liveness:
                type: HTTP
                path: /
                port: 8080
              readiness:
                type: HTTP
                path: /
                port: 8080
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: gatus
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - status.gismo2004.cc
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        type: configMap
        name: gatus-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
