apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:pTLow7NKwMC4M+fMmHX1qjh6MCsqtvRTlm0Ed5bgjBw=,iv:O+z6GPg368LFp1z5DnFPNECf8jurQUD1S0MFLkKi65U=,tag:HLWyvyMy/nS8jnW533LIUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFY5QU9KQkFG
        bnpNQWJEeFZkUkFtUmszanJJU2tGQyt0UlI2bHovblpLVGNFcm1nNUJFR0pzb0hX
        VGtUK0R3VTlVc3dURGFCSURLZzVSbHdTejQyMUtIcXdYcU9mYXVVaENtNnFkWVg4
        enJVWGY4VXBmTlZFYW1Fd2YrYS8yTDVOSGNJcGpJaERaTE50eCtXbGwrY0lCWWJu
        T0F0cjM4WU5TQVRKS2VtOWgwUXJaQjdscnp1ZTJhMStGRThFN1BIb1MwUEpKYldH
        bEpXc2xPV20rRGRTQTllYUNBR0p1NGp6bWZmalNCM1MwZHFMNXFiV2FNeUZ5V0FP
        OE9BeE1wUFhEQ1NLQU9pSEdNMjhnZjRLWDdPTERORWhML3h0UVR0bi8zM2IxZk90
        Z2o2U1ZaZCtnL1p4VFlUWDN4RHlsMTJLVktIdmRBYjgvc2pYQllJOUNOdFh0NVh1
        aVBZU0NHUWZmUzJLcUVIUnhxaTM4RjYxYVVrZ05IUWFrNDhLaHN5OVNvajRNWVFN
        UWFnWXJid2p5WGhodTBXc2hWbVUzTnFGRmhDeFBUZEl5MW1VZFBhck1wVmpQZGgr
        aW1GRmxDeEJaRlRJcnFDcmxQbFFPQmt6b3l1VFo5dHlVRDFYcVRlaGV6L1llcDdr
        QTZFWmRNQmduSkl2VXN3UGJoMHhHQTdqNDBIWlFSTElvcDlyZU5DU3lMTWMzQkNX
        aU1rYjI5cG9DUlBWSkp3ZUg5RVlIUW9WUjlUeUdWeXJoTWttamt6R3hMVzl5L1ov
        eE51d01hZ0xjRDg5aURLT0V3VXc4Qjd6eEFCY0dCVmI2UC9SaVMrOFY2NElTdkZh
        c1hTQ0hwcGkxd1Y4ZEt4YmdEbno4MlpTNStuRHhTa0F0d1RsYlpNUE1IYWhyN0Jx
        T0c0N0RXblljNnpRcDNKSThEWXV4cGtUUGtvQ3RzNHZzTDNLL3o0ajhoRHA0YzRW
        OXFaV2hZdm8xODl6aURtUWRDb1pVZHB6ZytUWVhXMzQzQW5XaGlLdTd2NXlTOTVU
        YW5XSzZ1eERnaWduU2poSzlya3pZS00vMU1wUmVtTW1TNGljdEU0dHlLdjBNcUpS
        WlQzMVFiY1hqSXV2enF2TW9EZk16ckcxcUM3b0VKRG5XTlhDc3E3S0xYSlFDV01D
        d3JSVjI4eFBxQUJXby9jc251TDVvRkQ4aVlBZDU0TVlYbDFoeTd5THd0UzlBVlJM
        QVpVQllmSnBxQlI2eHJZYUhWTWk1TzlPb2dKbnF6ZG1OeTgrMTFjTDZReW9ZV0xx
        UjlyTG5TTS8zNkFsVjBkWmljRUl0UGJ6YWV5WFNFaGFWdDE2algrZ29zV3pBenlG
        blNGVXp6R3NoZ3RTNHc0TE9EQThPd3NoUEFibllpeGs2VkJIa040c0hBeWU0MzZI
        WFQxc1BtTXNhN0NISjhIRFBPT2llN3dlMTVxYWFWOFhJNjRwVWdUVkNqeDZ2b0JQ
        L1BwL2tSYkZYMGdhd0xRODNScVJvcEtkMzAxY3A1b05nUU9jNTlNMHcweTRzVzJI
        S2FVYVZ6eXlGYXFoQWJMNUtpSGh1UmNjMUtDamNYZG01RVBFc2RUWWFMNnFKM2xs
        NkRKZk55ZmxFUjNoKzhCTThUdHRHNDhOY1JyV1JCWEcvcDZEWncyMHZkWUltMURZ
        WGtrZWtjd24zMm1UeWd6U0lFZzlTc0ZjSy9BRDgyamlFYXMyeFhJK1pzcERLNWRt
        Uk1LMWptVm5HVkJrYlduRmhYRERWR0RzZVF2cUZTUUhTWEVwbnBWTitEYitGN2g2
        azhjY3ZLNjBvdFQvUUo1NTgzeHEvUTh2YVJCVEhmSUZQbm9BclNmaGtMM0d3NkJR
        bzVpeEpKeUQ2Nk0rdTFUbDNKNmVaK1M2bnhLVFZxdDVoWWtTQmRCd2hZRGd4cHdI
        dG1yaUlVWlh1a0hSUjVVTVJBRWE4cTJpWnZKVTZIZ3U3MUFDTEtKZk1GQ3dOdwpR
        QmVTVjFvWitNdzQvelN2Tjk2RTIxRXNyUHZ0WmtXUmR3Y1k1RWtXeVBRCi0tLSBj
        RXgrY1hKY29rMEtwWlpGbitBbmZtRXI2eE93MEQrRDFUbzJ2bG5EU3FJCrDclB1H
        cmTmJ6207JKsXaNIZ6tkL2GEslvBlRIZOq/PHTrgnjJZJXNzGvNLIEZ+lkBwKljp
        2JxsIKLYQHBN7Wo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T19:39:57Z"
  mac: ENC[AES256_GCM,data:qMZEttZthH4vc6N2mGHcpre6ZKblQ3LdPVIxMfjhBA4uhAXUx+TAenTRJ34Uv+rnJZr95mqVlhWzj5te8pl5gz3I1C/4bCCnPga6WXY9+OKoyGGIsB+PNYSCbXB8boWP/GFU+LL57KcAQQCmb9Vj8dcJV+5DvQxzA9HfDDcUWf0=,iv:uzeWMMIFkps4Yn3qoZjONj6/BmZA84eboeP2R90NO4I=,tag:PUgF5Npf988rq+pYKJws2Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
