apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
  namespace: o11y
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:tfgqSDMgDWKsy4TWuAuwjkM+mRhGLRT6XpCEEkD8G+Y=,iv:i9uINAqcBDE5VveQiLJbyxPSj5W1KjWk3A3xKP8ql74=,tag:W9kcwONn8ueTh5wOgg7mLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhVY2JwOEEw
        VjRNeVBnTzc3N2VrZVIwV1Y4NHVLNUpxYnJGazVsblQ5UTVzSmhsK0JKZE5vc2hj
        MHNIMzlidzV2RUY2VUhYTFJqdDNFNGs4T3dEd1o4K1J4cFRseE0ySUw3TUVJV05z
        ZmI0Rm9iS1BqeGpyakl4ekZ5UElHcGdiY20zTVdHdjMyVzZGMFFod2I1ZFRMNysx
        VWV6clhGc3lSZFFWa2hxUlJhdWp0djhVVU9DWGthM3NQV3hFcURma2ZUT1V3ckdM
        VStNK2xvM01tb1JkWTMzeXBBWkdGV0ZWZi8vOVppbERXekFGYjNwZFgyUUFoMzFj
        dTYyT2dFQWMvT2dVM1RSc3dTVWU0M3pYZTZEMDVzc0RHNjlJbDNWZjY2SjJHZll6
        M01vNi9WOUVPaWlqSFJpUVRhY093Mmtnb0czY0NUWW9LQUNRMDNrWGFmM1d5b3M5
        MVkrMm5vZ2tmSVVlcVo4WngxK2xSbGNKUk1XbXJLQUZsOEt0L092R002aTNvbitu
        aWlhVUg2bzlMVHlrRmFPSC9NQ1dHb3hHL2FONFF1TUdSYTF0ZDJWSlJRZURNWDB2
        R1dkd0JWR2pNS3NmVGl0REtVQ3VuVTdVMXlMdzlwUTlUNzFSNWhqcWdBVGhoVmFO
        Q1dPR0xLOXI4K2dRSXRXQW9wZlVwcWQvMkNpU0NhQmRWRmQ0UGZiNDdKMDVTTnQ4
        UkNseUgrUEY2alBRbTR6cHgzTWQ3QmtMTCtEZEVaMnlCQ0V3ZGt6Y2daNU5RRWhr
        dEZsVkp4UitwTEp3U2s5QTNUTDVMNEVRZGlPaHhPQ1N1L0xiM3hURVhDSVpaVzBz
        OEdpV1FFeFNtUmZWalN1eTk0VkxVUWtYeUNiZ08rb0JYdEtRRDluZXFSQTRySWQ5
        bUZuNThHeXdPOUtsM08rSWM3S2R6NFJXS3dQVXNxZHM3dDhja0NRbStuS2ZQTE1M
        VUc2dEVhL0RWbVArVjVLSjd4c1BWaldoa0syMUM2YldGVkZySmJLUkVpZ0R3NzB5
        d2xEa2xTa1FEdG91anhkT05US2F4VndCcDArZHlYcU14T3BFWlE4NllMSU1CZUF6
        MjllVFpaNHdCTVhPTGY0eWE3N0poNXdCL0lEQTlZdEo3SXZlYU5aeHdLdGJHemNa
        dTBZQ0cydWlNT0dyUE5YVFIzMnlhNWRqQURGTCtEOXVodzJZNExUMXJHeG12R1pH
        eENyd3FoZzZZOUFURytIT1RCd2VKRWVsdUNPOHZtQUltUnc4OW10enhQNGxoNm5O
        U1c3am5BU3NlUWkvZmRrL3dwOHN5ZDRlZnJkN1NGMitvL0lxQXZBRzNNMi8vYUVt
        cjIxZ2E0ZE1sV2U1c1BYM2E1Y0lFblNxbWtvdUJsM1QzUVp2L0lTeEp0TEhOdGJU
        REIrWXlrbUliMGNIVW9ZcGNrbUJ5N2FMcmRVUy9lbS96clhqMnNFbGNQNFJ6djFa
        VTl6RlJDekx5WHFUOXNxSFJlZmdYUElya2xheXhtUDU1YmgwTnBZQUpkTUhaei9x
        ckIvRGxkL0Rocm9kdmVoN2lod2xRV2dxUWZ0YU01OWVGNjdUQjB1dXZ1K3JNTDJr
        UElMWEg1bnJNazBsa3dTSTN2M1ZmTisrWnNKM3E5Y3kxYVFRbk16Y05OV01mUFVv
        RC9LMHUvaWVYR3dKL2UvVGhnRDQ4SkVXOGZ5K0VlR2FqTTYyRWZpUnpSNzFJdGJW
        WjY2R0pDZm5HSVo2NUVGK2pFU2orTEJvcUJDZlFiVzQxQTVoWVJJbzZ4RTVxV0VB
        M3hYWWpRZXFOZ3F5RU1ld2ZuaHk1RDAycklNR1AyRFJzQ3ZSU3Y4Tk51RkM3TGJR
        amNBYW1IeWg3ZDlCNlVTYzhSRmFMVjRibXl5Zk1WeVhxRGFJUkw5N0VMMUpxV3FM
        dzB1N0pac2pwQlpkZ1E0N1ZkK0ZMQzdJOUowd0s4Q1pEb2VweE9TQmpCSkNaUQpD
        UUlrTTRtQjFET0J4NGtJcHZKUnI1ejJLTkxiU1BERklobVp3MVZIMTFBCi0tLSBq
        Zk9YTVl3QWhXT1ZWS215SlNRK2VPaFlKZ0d3OHpzWkllVkk3MUhKUTBZCpa5ZdOW
        m+84NjpOH5dDzOn7HvhzEqXp3nwExVMx8nRGHFWbMAR/VOg2FBcQyX/OM4/Ux6oh
        ezBd3B1OvUARfFg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T06:46:11Z"
  mac: ENC[AES256_GCM,data:R2ZRN1IPVdwsEs7S616kb8XsCYTgeK6rpBqGgO7Lvv2c2FvVXJhLOHxHzpdU/1dyYZBKk4BOQ3nML/hA/Cz/3iJ0WdsjKYGd5bYsrZICybrDi7bvpRdVUMgRVoXuxijvMpQx98FrhWxn7TjyJbBqQ8DwznN9Usa6D7bxnMn7VAk=,iv:2zh8+WKBlA6xw406VeTLQRiTERUKx6OnkaGDvnFky8k=,tag:8hgBXrASB5TP0kPaLXeyfQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
