---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "gismo2004-cc-production"
spec:
  dnsNames:
    - "gismo2004.cc"
    - "*.gismo2004.cc"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "gismo2004-cc-production-tls"
  usages:
    - digital signature
