---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmoadmin-data
spec:
  accessModes: [ReadWriteOnce]
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: tasmoadmin-data
  resources: { requests: { storage: 5Gi } }
  storageClassName: miroir-local
