apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:gGCAm7z9RlzCz1eg3gAWqdhTKvBXM06m4Ji6CZErdw8=,iv:vp0yDuvRvKJyHPHW7LbnWih6YnAzEMCRgJpAAiYjocY=,tag:nSFhUHWz6xRitAXihRhp0A==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:YI1U+IldEBPewZJfdbaYM4uQNG5H6oqpd5CddqYv9M8=,iv:keUibilUL/sp2qRHoHh52/UBVKF2lHywEATeLbgQ9hI=,tag:Bi/tSYRpDodJYHshC41A9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlycXhkNm1a
        QzNKeXM0cHJsaXA1TmpLU045Q1Y0MG1hdG1xK0xMN05VamVORnZnRDdUUGUxaWVM
        c2FSYWJQZHN0amprcDdVVElvSHNSRGpaa0I0cm1oWDFNYVAxaysvSU9Pb2QyZG5x
        V0g1VWp6cFQyaFAyckFwWDBSZE9vdnN5Ri9zV2g4eVdoU05PaXhCcitOKy9UQ3ly
        STd4SXNITldzQ3VhU3ZsQ0o0NG9rSlA1RVN5Zm44VmxRQTBjeUJ4SmI2SUVwUWk2
        SUVIVVl6dFV5TWRmdlNaaG9hdklmU002VUUxZHVORVgwTzA4akJuVjB5VUVwYnk0
        Rk5mK0FSZGlVTDRwRHJ6d0pSTlpUZTU1VlgzSTFNT0p2SWRpMnZiQkpuNG4zSnV6
        KzR4dEJoZGVlQ0tLMk9BNXFsZWJFK3JqRWErQ0RPNXB3WGlIbHkzMld3NmlSY0RF
        NU51cFh0QTUvMHYyMEd1di9rMWdFRmFaYUFKVTIyVjVOenhoZURhRlRaY1JPSFJz
        VjdxR3IxQzRmL0c0cFBzWWlYMU8rbU1CK2VESlAzd0c3UDhobENLWm0vbUZ3U1ZD
        NjkvL1IwS3BnejVOYTFQdUR5YzU5N1J0RFk0VU9FbGRWQTZEU3pGeG1YOVphUTdT
        dkM4ZDFaWEIrQ3VJU1lkQ2hDMXB6d1Znc3NyS2E3NTBKbEc4SXJqOWJGWkI3YUxp
        ajZ1bXFhaFF6NFR0djZ5S2FiSnR6SUJnVWl4Yk9mZXRZcEhGanV0NWl0YXpJdzZX
        Tngxd0F0aVFyakZSckJtNGJaRVdVRTBXaXkwUmcwNTdWYmNRWWdZYitXZk16TEJv
        SkNueTdDMURpTDJmelM5S2NLeFpaaGtJWnlLOHVlVi8xUkdaTEVXcmJHK0w0WmdB
        MTVCSHJuR3h1YzZ5Q3A2MzVwV2twenBYVWdxcVVWSk9aNWdvT0RtZ1FuK3ozMXdL
        cFNzR3hkSUp0Q0VxUHN1RzM2NTRMeXd4Zkl0anVaSHB1WHY2UExtMVpCeFlXQ2ZF
        OS9VMkd1RGRzWXRyWHlwa0FaUENzWm84eGpoZ282YUtoNnU3eWQ0dGRDcVpWYWlx
        OHo5S0s4clhFRWlGS2RhekJ5eVFmdVdHS2sxaWxOMVQ5Vnp3NGRrcEFCQ2MrT1By
        Z3I3a1llY0tVcU1TbjcvUzU3ZXRsVWwrMGlMdFpRaGVjeUpkWVhpMVA0dDdQbGs0
        Q2gyWEM4Vk44SmpGb2RGdjhOZ3g2b0FveTZIeEJEUWtnNk94VldUMklzZXZ3LzJL
        U2RmbHdMSmdwVzE5R05wQnZYUmtnZkQyM0c0dmVJZGo4ay8vdDdVWVBScDdTbXhX
        bjQ1U3B0YzZ0Snc2eW10d1pSY3NYM3ZuTnlMVzBqWkxKcjNhbXNSbXJyYWdZZEty
        cEdoekVsY1JGUXFMc2xtenBEUmZtQjgrV1pFM09xazQxaWgybXU3ai9EdGZoQVRt
        S05SMXROb0lxMmlkc0JZdGN2Slk3cXhNWm1DQ3dHMnkvdDdWS29hNTF3NFhwWU1l
        VjAxbWFsL3NYK0NVR05EelMxY1Z2ZWc5TlpObUw1aTJMaUtNUVcyeGtvUXg1S29V
        anA3U3I0MzNsdytRbHAxS0I0RVVYOEdYOTU1Vkx4UVR3Mlk1MS94T201U2syWUNW
        SC9zTjFSZjdReWc1UkRPVFdzZ0FYVW1idlZyY2pIV0UzMmpaS3hvY28zUk9PeTln
        djMwdmJQUWFHYmRmZ1c4RUlMRWRKdEw1OWNIVzRHUGFUUnhtOEtzR0k2bFR6N3FG
        VWN2cnhsVEI3eFJBMmUweUpnVytOekRiNWhhQlY5S2UvQWJHTXB3bnNRTmZLd2ZU
        czN6YzIyNFV0VnRtRjBFcHJxem5CMElsdGVkV2FvNFpsRjdOVjBhb2NLL0xGUk1B
        eUpmMmVQUmoxRVlnQVp3WFpGcmo5ajJvY0JaTmJSYmdlNkg5WFVVUWtDNXhRZwpy
        QldzalNrTFZqczNmblFPSFlyd1FKdkJ2NTROUDJ5SUpyWG50N2JlS0pnCi0tLSBr
        N3ZjUFBzQ2RzRFdGRE5LWXVSYUdXUU9ZNjVtV0FZbUV4ZS90cHp6WURJCkO3q8rB
        +yIu3XxPTBefi6yE0SOi5c9Ac75TluIVunAqeJl0ifDpYlBKokmtBpZjbUZ1lAws
        jg25RFPkuKlbdB0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1zxsrtxle3j9q33fj2u3tayxvjmakj0rfw0qhwdeql96gwuntnt220tdv8en6485vxq4vj6aanc9ccp3hcdjhwg4fsp09nz5gldv264tz4nu9tqmq9wsjwmrq2hdkszvckcw0sxgtcgrtta6lm94fydmn3gyp884500rsysnglgqgv8en27u8grp6wyjkhxq7zzg2lvxgjwrjj3ancf7trk3tyqqxt3zx0pftenqk6qrsegmdw6gt72jgcws3kmsgnw7eyyg2u3mswx5u8qlnx6k4zu4kqg3jsdyxhj6gh844gl44z45w7u4fmw32akrvzp05gs6lgp8alecuqfpnmqer0zeg5cq50f0xl6qzw4tsesrj4xalq2jxqfrfhg7xxykyuc989qpj48hs3wxqr9rn8p353p7qt29uyha8m0r42f9cfaeh8wem4dc2eq4mgyhlck4z28y4pcyk8ezes89jmg5n75ae7m44vp2ue3jucy55prqusyqldw5hkpyt86hwwf8z6j8aa4ewwq2g53ys2txa9rc4pwssu42lp74evzzhznr00xsfc6zjjkrp4ltku2drr5ltnr0cp9sjavql4kagfmvkvhx7cx2yhrqvcvcgakg63g5s353yyxakgqpl8xsdslauujxrr34rrju3qaltxjf8ntgvy383evw5qtwk5qxfg9yg0dumwgm5ytmvk8cscd7wmsepl2ej9h9hpj80qz464yy8zgn6ejxz0uuj2mgr5fsaywd8yc33hjamz9jvym29zxanfs05j4re57wzwclzd7cepq4qxezfz6a8pt5hz74jkww4x3440rqrrdusg45mqz03hulrgc8p8gu0ugg3dxv4pcr5xx7qkh3gmnxjltyswqrndzdh42gp0wpxw9ymhwfqwv64t4xrsmmefqdsrstuvwv4njnytjrypj8dv75skjwkkqjcxgf4yhl8zd29wecdq2atrzen90kpput98a7v8wqqucvau9uustw9uuyqx7kzjedhj994dc45yr25uj6gz9ekvfuhkde4fwgtujgh3e9f82tukncqe9v9synz4d4m0yyz4a64znnzyxtune3cgae65s2px9pc50vvqad5mycvsz539f9v0fhxcy04tjz48tpgtjv2wnf2pasu5s95afyk6jk05xyhra22epemkh0x5z0fjzeztmnqlj0rs30ase2w9p4xznyljzjr7wzqerl62xmuuvwmg7gnnk6pz4zt2htp3nglsjh4t9el5qg83r8ts74wwu4ks2vc22tu4hmntsa8dxu92fmw2k2ysyj6cjse38xs4ekcdxeexdf9s9sxvefuq8mjq23ahpwfx46ydje5clqhuvcnh20zzcpw8y84hepfal6jqtk5j3vtggxdzdy3q592n3pr4c0398pkvvj6yv8xep6xwndczqr3cvnwkwhv2dw6y95updem6z46dk33z9jlkaceccrhwun3zla99u4adf4daq44eycynjtn7dy3g7r3kqpa0jf2dqrzckj3py2rc85wpjvcrftlhut8gtqtr6yt0pryz99u6xm8tt9alaf3pstkpjgfx8fgly3m77drgj9qc2ph2hqmksgqt5lxhz3jt3trp4qthzh58pssc3ve5729zldz5e8t52awgvmqwk9alwsf9eye29jj359ncajuc09l9yvtnvuh0ay9qttln8kscax3jy43xa6c3mhsx35ezysug7qcnuyr0u9rnefxkklr3zul4d6ksu9z4epufdfukecdxzfdcx3yk4wvpl5skjzvfs28y8kr2jrg095kg2cfjp04fu0fddmuu4r9f2glv5g2gu7397emac322ev8305hctakycl826eyh2ax65sznrwu06wzpzduwv6qj50rh2acghqy0llegt474fht23ynkrwrvm67w54pxshc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T19:39:58Z"
  mac: ENC[AES256_GCM,data:6BG5SX9kuowKdi/Sv8kUjtkLya1u5rZXIn9qxsQUjpmVVNMuibzyQo8kfgnbu14BjyltRZgjz1L2EIsOR2z4YVqbQn/co0cvXJqzIlLS6bc2syl6fwi1wi8PbnfVrIJ+JtuaP2Fpz9GDJlBL7eNfwOYUqxeePmcK/j1FJBK+9hg=,iv:PCnP7hXkxa7kfiPftGTOlHT/KGYL7osGaKRLp4tjmos=,tag:K5EwfAf0vkyU0mioE88jQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
