---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-service

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./octoprint/ks.yaml
  - ./pve/ks.yaml
  - ./truenas/ks.yaml
